<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon />
    <RootNamespace>FileConverter.App</RootNamespace>
    <AssemblyName>FileConverter</AssemblyName>
    <Product>FileConverter</Product>
    <Description>Windows movie collection video converter powered by ffmpeg</Description>
  </PropertyGroup>


</Project>
